---
- name:
  set_fact:
    ip: 13.235.11.202
    path_of_artifacts: jenkins/jfrog.py
- name: delete artifacts
  uri:
    url: 'http://{{ ip }}:8081/artifactory/{{ path_of_artifacts }}'
    method: DELETE
    user: admin
    password: test@1234
    body_format: json
    force_basic_auth: yes
    status_code: 204

