---
- name:
  set_fact:
    ip: 13.235.11.202
- name: delete artifacts
  uri:
    url: 'http://{{ ip }}:8081/artifactory/api/system/storage/gc'
    method: POST
    user: admin
    password: test@1234
    body_format: json
    force_basic_auth: yes
    status_code: 200

