---
- name:
  set_fact:
    ip: 13.235.11.202
    path_of_repo_in_trash: /jenkins
- name: delete from trash can
  uri:
    url: 'http://{{ ip }}:8081/artifactory/api/trash/clean/{{ path_of_repo_in_trash }}'
    method: DELETE
    user: admin
    password: test@1234
    body_format: json
    force_basic_auth: yes
    status_code: 204

